apiVersion: v1
kind: Pod
metadata: 
  name: sample-pod-conf
  labels:
    type: back
spec: 
  containers:
  - name: sample-pod
    image: mmumshad/simple-webapp-color
    ports:
    - containerPort: 8080
    envFrom:
    - configMapRef:
        name: app-config
    # - name: APP_COLOR
    #   value: pink  
