apiVersion: apps/v1
kind: Deployment
metadata:
  name: niginx-deployment
  labels:
    type: front

spec:
  template:
    metadata:
      name: front-end
      labels:
        type: front
    spec:
      containers:
      - name: nginx
        image: nginx:1.12-alpine
  replicas: 2
  selector:
    matchLabels:
      type: front
