--- 
apiVersion: apps/v1
kind: ReplicaSet
metadata: 
  #namespace: dev
  name: myapprc
  labels: 
    app: my-app
    type: front-end
spec: 
  replicas: 3
  selector:
    matchLabels: 
      app: my-app
  template: 
    metadata: 
     name: nginx
     labels:
       app: my-app 
    spec: 
      containers: 
      - name: nginx 
        image: nginx:1.12-alpine
  
     
