apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: niginx-front
spec:
  template:
    metadata:
      name: front-end
      labels:
        type: front
    spec:
      containers:
      - name: nginx
        image: nginx:1.12-alpine
  replicas: 5
  selector:
    matchLabels:
      type: front
